name: Bucket Compliance Check

on:
  workflow_call:

jobs:
  bucket-compliance:
    name: Run Bucket Compliance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Install dependencies
        run: pip install boto3 pyyaml

      - name: Run bucket compliance check
        run: python scripts/check_buckets.py